spring:
  application:
    name: shelf-service
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        default_schema: shelf
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

shelf:
  update-cron: ${SHELF_UPDATE_CRON:0 */5 * * * ?}
  reset-interactions-cron: ${SHELF_RESET_INTERACTIONS_CRON:0 */5 * * * ?}
  recommendation-size: ${SHELF_RECOMMENDATION_SIZE:10}
  popular-size: ${SHELF_POPULAR_SIZE:10}

event:
  service-name: ${spring.application.name}
  bootstrap-servers: ${KAFKA_URL}

eureka:
  client:
    register-with-eureka: ${EUREKA_ENABLED:true}
    fetch-registry: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}
